### ISSUE TITLE
Option to iterate over alert groups?

### ISSUE THREAD

**Issue by filippog** [knyar/phalerts#10]
Hello @knyar !
at Wikimedia Foundation we're currently using phalerts to bridge the gap between alerts and phabricator. We are experiencing the following issue: certain groups of alerts might require opening a task per-alert within the group, and this will also unlock being able to use alert-specific values when templating alerts.

To solve this issue I was thinking of adding the option to iterate over alerts within the group. In other words individual tasks will be searched for and/or created as needed for each alert in the group. Is this functionality something you would be interested in having and would accept PRs for it?

Thank you in advance!

**Comment by knyar** [comment]
Hey @filippog, I am excited to hear that you folks are using this tool. Even though I am not personally using Phrabricator anymore, I will be happy to review any changes you'd like to make.

Could you please help me understand why you are grouping the alerts in the first place if they are supposed to have separate tasks created for them? My understanding of [grouping](https://prometheus.io/docs/alerting/latest/alertmanager/#grouping) is that it's specifically designed to ensure that several firing alerts only result in a single notification, and creating a separate task per alert in the group seems to be the opposite of that.

**Comment by filippog** [comment]
Thank you for the quick reply and support @knyar !

To expand on our scenario: we have [`ManagementSSHDown`](https://github.com/wikimedia/operations-alerts/blob/master/team-dcops/mgmt.yaml#L6) alert when the management interface of baremetal hosts becomes unreachable, from this alert then tasks are open for datacenter ops folks to work on. By default we group by `alertname` and a few other labels ([alertmanager.yml](https://github.com/wikimedia/operations-puppet/blob/production/modules/alertmanager/templates/alertmanager.yml.erb)) not to get spammed with notifications for example.

However for a selection of use cases alert -> task for us it makes sense to be able to consider the group alerts individually. Case in point above, we would like to have per-host (per-`instance`-label) tasks open (e.g. with the hostname in the task title) while keeping the alert groups.

I hope that helps clear up the use case, please let me know if I'm missing something!

**Comment by knyar** [comment]
Sorry for the delay here. What you are trying to achieve makes sense, but I am still not sure I understand why you are not using alert grouping for this. Alertmanager supports setting `group_by` [per route](https://prometheus.io/docs/alerting/latest/configuration/#route), so you could do something like:

```
    - match:
        team: 'dcops'
      receiver: 'dcops-mail'
      routes:
        - match:
            severity: 'task'
          # Default to #dcops project if none of the site routes match
          receiver: 'dcops-task'
          routes:
            # new route for per-instance alerts
            - match:
                alertname: 'ManagementSSHDown'
              receiver: 'dcops-task'
              group_by: ['alertname', 'cluster', 'scope', 'team', 'instance']
```

Instead of matching by alertname you could add another label, e.g. `alert_group_by: with_task` and then set that label on the alert.

I guess changing `phalerts` might make sense if you cannot control your alertmanager config, but if that's true perhaps one of the existing labels in your default `group_by` is not actually being used? Then you could fill it with the value of the `instance` metric label, expanding your notifications to one per instance. Something like this if you want to set the `scope` label:

```
      - alert: ManagementSSHDown
        annotations:
          description: 'The management interface at {{ $labels.instance }} has been unresponsive for multiple hours.'
          summary: 'Unresponsive management for {{ $labels.instance }}'
          dashboard: TODO
          runbook: https://wikitech.wikimedia.org/wiki/Management_Interfaces#Reset_the_management_card
        expr: label_replace(your_metric, probe_success{job="probes/mgmt"}, "scope", "$1", "instance", "(.*)")
 == 0
        for: 12h
        labels:
          severity: task
          team: dcops
```

If none of this works I think it's not too difficult to add a flag to `phalerts` that will expand a single notification into multiple tasks, but I'd prefer this to be a minimal change (e.g. keeping the notification template the same). And tbh it still seems a bit hacky to group in alertmanager just to ungroup in phalerts a moment later.
